Add stablecoins mint and burn tables
duneanalytics/abstractions pull request #165
Opened 2020-11-21 14:36 UTC by milkyklim

I've checked that:

* [ ] the query produces the intended results
* [ ] the folder name matches the schema name
* [ ] the schema name exists in Dune
* [ ] views are prefixed with `view_`, functions with `fn_`.
* [ ] the filename matches the defined view, table or function and ends with .sql
* [ ] each file has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

2020-11-21 14:38 UTC, milkyklim commented on schema/stablecoin/mint.sql
> +    SELECT "name" as project,
Using stablecoin `name` as project.

2020-11-21 14:38 UTC, milkyklim commented on schema/stablecoin/mint.sql
> +           "version",
Is everything except Maker `version` 1?

2020-11-21 14:39 UTC, milkyklim commented on schema/stablecoin/mint.sql
> +           value / 10^st.decimals * p.price AS usd_value
Is price necessary for stables?

2020-11-21 16:13 UTC, mewwts commented on schema/stablecoin/mint.sql
> +           value / 10^st.decimals * p.price AS usd_value
@hagaetc

2020-11-21 16:13 UTC, mewwts commented on schema/stablecoin/mint.sql
> +           "version",
@hagaetc

2020-11-21 16:13 UTC, mewwts commented on schema/stablecoin/mint.sql
> +    SELECT "name" as project,
@hagaetc

2020-11-24 07:19 UTC, mewwts requested changes

2020-11-24 09:16 UTC, hagaetc commented on schema/stablecoin/burn.sql
> +       from_address,
Should be `to_address`

2020-11-24 10:36 UTC, mewwts commented
merged here https://github.com/duneanalytics/abstractions/commit/0a9bef540441035e09fcd762dcb30d24fe44b578

2020-11-24 10:36 UTC, closed without merging

2020-11-24 10:36 UTC, mewwts commented
Thanks @milkyklim