fix tokenlon traders bug
duneanalytics/abstractions pull request #375
Opened 2021-06-07 11:58 UTC by focusj

I've checked that:

* [ ] the query produces the intended results
* [ ] the folder name matches the schema name
* [ ] the schema name exists in Dune
* [ ] views are prefixed with `view_`, functions with `fn_`.
* [ ] the filename matches the defined view, table or function and ends with .sql
* [ ] each file has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

2021-06-15 13:14 UTC, 0xBoxer commented
Hey @focusj, in our eyes TokenIon is a aggregator that runs on the 0x network and therefore is correctly slotted into the "aggregator" category.

Please provide documentation that you indeed have your own trading pools if you think you are a "dex". 

Otherwise please change your PR to keep the aggregator tag instead of 'DEX'.

2021-06-15 13:15 UTC, 0xBoxer requested changes
see previous comment on the main thread

2021-06-16 02:13 UTC, focusj commented
> Hey @focusj, in our eyes TokenIon is a aggregator that runs on the 0x network and therefore is correctly slotted into the "aggregator" category.
> 
> Please provide documentation that you indeed have your own trading pools if you think you are a "dex".
> 
> Otherwise please change your PR to keep the aggregator tag instead of 'DEX'.

i get you point. Next release Tokenlon will run on a new prototol, for now i'll change it to Aggregator.

2021-11-25 05:28 UTC, masquot approved these changes

2021-11-25 05:29 UTC, masquot approved these changes

2021-11-25 05:32 UTC, masquot approved these changes

2021-11-25 12:12 UTC, 0xBoxer approved these changes

2021-11-26 06:37 UTC, merged