Balancer: liquidity views
duneanalytics/abstractions pull request #459
Opened 2021-08-30 20:56 UTC by mendesfabio

I've checked that:

* [ ] the query produces the intended results
* [ ] the folder name matches the schema name
* [ ] the schema name exists in Dune
* [ ] views are prefixed with `view_`, functions with `fn_`.
* [ ] the filename matches the defined view, table or function and ends with .sql
* [ ] each file has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

2021-09-08 15:16 UTC, antonio-mendes requested changes
Oi @mendesfabio ,

First of all let me say you have a beautiful last name 👀 

Secondly I dropped you a comment on an error I found with `balancer_v2.view_liquidity`.

And finally, I pushed a commit with a few small changes:
- explicitly declaring schema names
- small fix that was causing me problems when inserting to cron

Let me know if I can help you further, and I'll keep an eye on this PR.

Cheers!

2021-09-08 15:16 UTC, antonio-mendes commented on ethereum/balancer_v2/view_liquidity.sql
> +CREATE UNIQUE INDEX IF NOT EXISTS balancer_v2_view_liquidity_idx ON balancer_v2.view_liquidity (DAY, pool_id, token_address);
I'm getting a `psql:view_liquidity.sql:325: ERROR:  column "pool_id" does not exist` error here. Could you double check and commit a fix? I ran the query by itself and saw the `pool_id` field was indeed missing.

2021-09-08 16:59 UTC, mendesfabio commented
hey @antonio-mendes 😂 nice to meet you!

I just fixed the error you found, thanks! Let me know if you find anything else.

2021-09-09 13:54 UTC, merged

2021-09-09 13:54 UTC, antonio-mendes commented
Thank you @mendesfabio!  PR merged and changes deployed, feel free to reach out if you notice anything weird