Add 1inch v4 (Own, Uniswap V2 router, Uniswap V3 router)
duneanalytics/abstractions pull request #529
Opened 2021-11-10 22:38 UTC by k06a

I've checked that:

* [x] the query produces the intended results
* [x] the folder name matches the schema name
* [x] the schema name exists in Dune
* [x] views are prefixed with `view_`, functions with `fn_`.
* [x] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

2021-11-11 13:25 UTC, masquot requested changes

2021-11-11 13:25 UTC, masquot commented on ethereum/dex/trades/insert_1inch.sql
> +            select "output_returnAmount", "amount", "srcToken", "_3" as pools, "call_tx_hash", "call_trace_address", "call_block_time", "contract_address" from oneinch_v3."AggregationRouterV3_call_un
On this line and the following ones, probably `when` needs to be `WHERE`?

2021-11-11 13:25 UTC, masquot commented on ethereum/dex/trades/insert_1inch.sql
> +            select "output_returnAmount", "amount", "srcToken", "_3" as pools, "call_tx_hash", "call_trace_address", "call_block_time", "contract_address" from oneinch_v4."AggregationRouterV4_call_un
This line gives the following error when trying to run it:
```
Column "_3" does not exist
```

2021-11-11 13:54 UTC, k06a commented
@masquot applied fixes, sorry about this

2021-11-11 14:14 UTC, masquot commented
No worries, thank you @k06a for all your great contributions! Could it be that I'm not seeing the new commit?

How far in time should the backfill go? Noticed you published the blog post about *The 1inch Router v4 Roll-out* on 10 November.

2021-11-11 14:18 UTC, k06a commented
@masquot sorry, pushed to the wrong branch

2021-11-11 14:19 UTC, k06a commented
@masquot yep, but trades started a bit earlier, because we tested it :) So you can use smart contract deployment date

2021-11-12 04:52 UTC, masquot approved these changes

2021-11-12 14:50 UTC, merged