Add Clipper Polygon to DEX trades
duneanalytics/abstractions pull request #715
Opened 2022-01-05 18:30 UTC by EdoAPP

I've checked that:

* [ ] the query produces the intended results
* [ ] the folder name matches the schema name
* [ ] the schema name exists in Dune
* [ ] views are prefixed with `view_`, functions with `fn_`.
* [ ] the filename matches the defined view, table or function and ends with .sql
* [ ] each file has only one view, table or function defined  
* [ ] column names are `lowercase_snake_cased`

2022-01-05 18:45 UTC, aothman requested changes

2022-01-05 18:45 UTC, aothman commented on polygon/dex/trades/insert_clipper.sql
> +-- fill 2021
Suggest to have two functions here - one to fill 2021 and then another to fill 2022 - present

2022-01-11 19:02 UTC, dsalv commented
Thank you for your contribution @EdoAPP 

Checks:

- [ ] token_a is the token bought
- [ ] basic check vs https://clipper.exchange/data
- [ ] USD amounts also for ETH -> not applicable here

apart from check 1, looks fine to me

2022-01-11 19:22 UTC, EdoAPP commented
@dsalv Thanks for catching this. Yes, token_a and token_b were inverted. I've updated the code so token_a is the token bought.

2022-01-13 06:06 UTC, masquot approved these changes
Thank you @EdoAPP, Clipper is now added to DEX trades on Polygon :rocket:

2022-01-13 06:06 UTC, merged