Yearn Dune Bounty
duneanalytics/abstractions pull request #917
Opened 2022-03-21 08:16 UTC by 3StepCapital

I've checked that:

* [ x] the query produces the intended results
* [ x] the folder name matches the schema name
* [ x] the schema name exists in Dune
* [ x] views are prefixed with `view_`, functions with `fn_`.
* [ x] the filename matches the defined view, table or function and ends with .sql
* [ x] each file has only one view, table or function defined  
* [x ] column names are `lowercase_snake_cased`

Order for chron jobs: 

1) 
view_yearn_contract_tokens

2)
view_yearn_contract_strategy

3)
view_iearn_deployments
view_yearn_harvests
view_yearn_transactions

2022-03-22 12:07 UTC, chuxinh requested changes

2022-03-22 12:07 UTC, chuxinh commented on ethereum/yearn/view_ironbank_aggregate.sql
> + NULL::bytea as cTokenCollateral,
maybe use all snake case for column names?

2022-03-22 12:07 UTC, chuxinh commented on ethereum/yearn/view_ironbank_aggregate.sql
> +irem.evt_block_number,
no need to use alias if you just have one table here

2022-03-22 12:07 UTC, chuxinh commented on ethereum/yearn/view_ironbank_aggregate.sql
> +'none' as address_two_type,
NULL?

2022-03-22 12:07 UTC, chuxinh commented on ethereum/yearn/view_ironbank_aggregate.sql
> +LEFT JOIN dune_user_generated."view_yearn_contract_tokens" yct on tt.contract_address = yct.yvault_contract
replace `dune_user_generated`

2022-03-22 12:07 UTC, chuxinh commented on ethereum/yearn/view_ironbank_aggregate.sql
> +tt.address_one, tt.address_two, tt.address_one_type, tt.address_two_type, tt."cTokenCollateral",
one column per line

2022-03-22 12:07 UTC, chuxinh commented on ethereum/yearn/view_ironbank_aggregate.sql
> +LEFT JOIN dune_user_generated."view_yearn_contract_tokens" yct on bo.contract_address = yct.yvault_contract
replace `dune_user_generated`

2022-03-26 16:03 UTC, 3StepCapital commented on ethereum/yearn/view_contract_strategy.sql
> +    "yearn_type" not in ('iearn_v2','ironbank','woofy')
Because they don't have strategies as part of the protocol

2022-03-26 16:05 UTC, 3StepCapital commented on ethereum/yearn/view_iearn_v2_deployments.sql
> +DROP VIEW IF EXISTS iearn_v2."view_iearn_v2_deployments" cascade;
in the list of contracts provided, iearn v1 contracts were not included.

2022-03-26 16:45 UTC, 3StepCapital commented on ethereum/yearn/view_ironbank_aggregate.sql
> +"accountBorrows" as amount_two,
accountBorrows is how much this total user/protocol has borrowed

2022-04-02 05:51 UTC, chuxinh requested changes
Really like how the final tables have come out. Most of my comments are nits and would like to see a quick turn around on the final one! 

Also thank for sharing the screenshots, i don't think they need to be included in the final PR

2022-04-02 05:51 UTC, chuxinh commented on ethereum/yearn/yearn_transactions.sql
> +CREATE TABLE yearn.view_transactions (
the table name should be consistent with the file name

2022-04-02 05:51 UTC, chuxinh commented on ethereum/yearn/yearn_transactions.sql
> +    INNER JOIN yearn."view_yearn_contract_tokens" yct on (ett."contract_address" = yct."yvault_deposit_token" AND ett."to" = yct."yvault_contract")
```suggestion
    INNER JOIN yearn."view_yearn_contract_tokens" yct ON (ett."contract_address" = yct."yvault_deposit_token" AND ett."to" = yct."yvault_contract")
```

2022-04-02 18:01 UTC, 3StepCapital commented on ethereum/yearn/view_ironbank_aggregate.sql
> +LEFT JOIN erc20."tokens" tok on yct.yvault_contract = tok.contract_address
Yes, we did need it for one of the token amounts - have updated it.

2022-04-02 18:03 UTC, 3StepCapital commented on ethereum/yearn/view_ironbank_aggregate.sql
> +WITH borrows AS(
Have updated it

2022-04-02 18:52 UTC, 3StepCapital commented on ethereum/yearn/view_yearn_harvests.sql
> +    ELSE (hvst."wantEarned"/(10^yct."yvault_deposit_token_decimals"))*-1 END as profit_loss,
Yes, you're right - going to remove case statement

2022-04-03 08:23 UTC, chuxinh requested changes
thanks for addressing all the changes. just two more changes requested in this review :D 

also cc: @masquot if you have anything

2022-04-03 08:23 UTC, chuxinh commented on ethereum/yearn/view_ironbank_aggregate.sql
> +            payer as address_one,
Can you also update all the `as` here to `AS` for consistency?

2022-04-03 08:23 UTC, chuxinh commented on ethereum/yearn/view_yearn_harvests.sql
> +    NULL as debt_payment,
i think you should keep the `profit_loss` here but double check what the `wantEarned` looks like and if you need to times `-1` for negative value

2022-04-04 10:26 UTC, chuxinh commented on ethereum/yearn/view_ironbank_aggregate.sql
>          (SELECT
can remove these brackets

2022-04-04 10:26 UTC, chuxinh commented on ethereum/yearn/view_ironbank_aggregate.sql
>          (SELECT
same here, can remove the bracket

2022-04-04 10:26 UTC, chuxinh commented on ethereum/yearn/view_ironbank_aggregate.sql
>          (SELECT
same here, can remove the bracket

2022-04-04 10:26 UTC, chuxinh commented on ethereum/yearn/view_ironbank_aggregate.sql
>          (SELECT
same here, can remove the bracket

2022-04-04 10:30 UTC, chuxinh commented on ethereum/yearn/view_yearn_harvests.sql
> +      ELSE (hvst."wantEarned"/(10^yct."yvault_deposit_token_decimals")) END as profit_loss,
```suggestion
    hvst."wantEarned"/(10^yct."yvault_deposit_token_decimals") as profit_loss,
```

2022-04-04 10:30 UTC, chuxinh requested changes
nits

2022-04-05 08:29 UTC, chuxinh approved these changes
LGTM. Thanks for addressing all the changes!
cc: @masquot to have a look too 
:D

2022-04-05 12:35 UTC, masquot commented
Thank you @chuxinh and @3StepCapital. Excellent work so far!

@jeff-dude can you please take a look?

2022-04-18 19:24 UTC, jeff-dude approved these changes
thank you @3StepCapital -- the code has been executed and merged & the cron job activated.

2022-04-18 19:24 UTC, merged

2022-04-18 19:24 UTC, jeff-dude commented
fyi @3StepCapital & @chuxinh -- i made a few minor commits along the way to get everything working as expected. hope this helps!