Update kyber query
duneanalytics/abstractions pull request #924
Opened 2022-03-23 12:43 UTC by tiendv89

I've checked that:

* [x] the query produces the intended results
* [x] the folder name matches the schema name
* [x] the schema name exists in Dune
* [x] views are prefixed with `view_`, functions with `fn_`.
* [x] the filename matches the defined view, table or function and ends with .sql
* [x] each file has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`

2022-03-23 18:02 UTC, antonio-mendes approved these changes
@masquot , I've reviewed and added a few missing UNION statements and was then able to run the SQL and get a result.

If possible, can you take a look and if it's all good, merge and deploy this PR please? 🙏  thanks in advance!

2022-03-28 14:50 UTC, antonio-mendes requested changes
👋  @tiendv89 ,

I left a few comments on things that need changing. Mainly problems on BSC.
Otherwise I've tested the Polygon (with a manual fix, but please push a commit with the fix I asked in the comments here) and Ethereum query and those work and return the expected result.


Let me know if you need any help!

2022-03-28 14:50 UTC, antonio-mendes commented on binance_smart_chain/dex/trades/insert_kyber.sql
> +    INNER JOIN ethereum.transactions tx
This should be joining on bsc.transactions

2022-03-28 14:50 UTC, antonio-mendes commented on binance_smart_chain/dex/trades/insert_kyber.sql
> +        -- UNION ALL
Uncomment here

2022-03-28 14:50 UTC, antonio-mendes commented on binance_smart_chain/dex/trades/insert_kyber.sql
> +    LEFT JOIN erc20.tokens erc20a ON erc20a.contract_address = dexs.token_a_address
The `erc20.tokens` abstractions does not currently exists on BSC on Dune.

2022-03-28 14:50 UTC, antonio-mendes commented on polygon/dex/trades/insert_kyber.sql
> +    INNER JOIN ethereum.transactions tx
Same as before, the blockchain here should be Polygon

2022-03-28 15:11 UTC, antonio-mendes approved these changes
Perfect! Thank you @tiendv89 !

@masquot , it's good for deployment 🧰

2022-03-29 14:43 UTC, masquot approved these changes
Thank you @tiendv89

2022-03-29 14:43 UTC, merged